### ISSUE TITLE
AttributeError: module 'bibtexparser.bibdatabase' has no attribute 'STANDARD_TYPES'

### ISSUE THREAD

**Issue by jtojnar** [rudrab/mkbib#1]
When I try to run mkbib, I get the following error:

```
Traceback (most recent call last):
  File "/nix/store/pr87agw4xvfmpby6v6sslflwaz89n59v-mkbib-0.3-dc90d7f/bin/..mkbib-wrapped-wrapped", line 43, in <module>
    main.main(version=VERSION)
  File "/nix/store/pr87agw4xvfmpby6v6sslflwaz89n59v-mkbib-0.3-dc90d7f/lib/python3.6/site-packages/Mkbib/main.py", line 459, in main
    app = mkbib()
  File "/nix/store/pr87agw4xvfmpby6v6sslflwaz89n59v-mkbib-0.3-dc90d7f/lib/python3.6/site-packages/Mkbib/main.py", line 402, in __init__
    self.MenuElem = menu.MenuManager()
  File "/nix/store/pr87agw4xvfmpby6v6sslflwaz89n59v-mkbib-0.3-dc90d7f/lib/python3.6/site-packages/Mkbib/menu.py", line 25, in __init__
    self.parsing = pybib.parser()
  File "/nix/store/pr87agw4xvfmpby6v6sslflwaz89n59v-mkbib-0.3-dc90d7f/lib/python3.6/site-packages/Mkbib/pybib.py", line 24, in __init__
    bibdatabase.STANDARD_TYPES.add("online")
AttributeError: module 'bibtexparser.bibdatabase' has no attribute 'STANDARD_TYPES'
```

I am using bibtexparser 0.6.2

**Comment by rudrab** [comment]
hi, 
thanks for reporting this. However, I am unable to reproduce this error. 
Have you run the `mod_install.sh`; `./autogen.sh`; `make`; `sudo make install`?
Also, you will need python3 for this. 

Kindly let me know.

**Comment by jtojnar** [comment]
I installed the dependencies through the following Nix expression:
<details>
<summary>Original Nix expression</summary>

```nix
{ stdenv
, fetchFromGitHub
, autoreconfHook
, pkgconfig
, wrapGAppsHook
, python3
, gtk3
}:

let
  version = "0.3-dc90d7f";
in python3.pkgs.buildPythonApplication rec {
  name = "mkbib-${version}";
  src = fetchFromGitHub {
    owner = "rudrab";
    repo = "MkBiB";
    rev = "dc90d7fe66749b9ff0a6259efed8bb376c5cc15a";
    sha256 = "0zl04nqqwjk7pnfxf6hfx5q3fawa7wck3zggbyrfxq9l8n07dh9m";
  };
  format = "other";

  nativeBuildInputs = [ autoreconfHook pkgconfig wrapGAppsHook ];
  buildInputs = [
    gtk3
  ];
  propagatedBuildInputs = with python3.pkgs; [
    pygobject3
    pypdf2
    bibtexparser
    requests
  ];

  meta = {
    homepage = https://rudrab.github.io/MkBiB/;
    description = "GTK bibtex manager.";
    maintainers = with stdenv.lib.maintainers; [ jtojnar ];
    license = stdenv.lib.licenses.unfree; # No license is specified
  };
}
```
</details>

Apparently, you are using a development version of bibtexparser, let me try to use that instead.

**Edit:** Yep, that seems to work:

```nix
{ lib
, fetchFromGitHub
, autoreconfHook
, pkgconfig
, wrapGAppsHook
, python3
, gtk3
}:

let
  bibtexparser = python3.pkgs.buildPythonPackage rec {
    pname = "bibtexparser";
    version = "0.6.2-2ce301e";
    name = "${pname}-${version}";

    src = fetchFromGitHub {
      repo = "python-bibtexparser";
      owner = "sciunto";
      rev = "2ce301ecd01f4db0cb355abc36486ab0c5c62331";
      sha256 = "0bjkr6s762si9vg5vyaksdq9bx12pmxdhd0zvjsfh203jka9jvan";
    };

    propagatedBuildInputs = with python3.pkgs; [ pyparsing ];

    meta = {
      description = "Bibtex parser for python 2.7 and 3.3 and newer";
      homepage = https://github.com/sciunto-org/python-bibtexparser;
      license = with lib.licenses; [ gpl3 bsd3 ];
    };
  };
  version = "0.3-dc90d7f";
in python3.pkgs.buildPythonApplication rec {
  name = "mkbib-${version}";
  src = fetchFromGitHub {
    owner = "rudrab";
    repo = "MkBiB";
    rev = "dc90d7fe66749b9ff0a6259efed8bb376c5cc15a";
    sha256 = "0zl04nqqwjk7pnfxf6hfx5q3fawa7wck3zggbyrfxq9l8n07dh9m";
  };
  format = "other";

  nativeBuildInputs = [ autoreconfHook pkgconfig wrapGAppsHook ];
  buildInputs = [
    gtk3
  ];
  propagatedBuildInputs = with python3.pkgs; [
    pygobject3
    pypdf2
    bibtexparser
    requests
  ];

  meta = {
    homepage = https://rudrab.github.io/MkBiB/;
    description = "GTK bibtex manager.";
    maintainers = with lib.maintainers; [ jtojnar ];
    license = lib.licenses.unfree; # No license is specified
  };
}
```
